// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rubhrcplvtmywnsaiusx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1YmhyY3BsdnRteXduc2FpdXN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNzMzMTIsImV4cCI6MjA2ODg0OTMxMn0.r_QJ4BwSnK3IRHXUIQxpTvq9awpun3nb0_h82bXZ8z4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});